# Generated by Django 3.0.5 on 2020-11-09 09:44

import dietapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='pic',
            field=models.ImageField(blank=True, default='pic/default.png', null=True, upload_to=dietapp.models.user_directory_path),
        ),
    ]
